# Generated by Django 5.2.15 on 2026-06-06 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('category_mapping', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'status'], name='products_organiz_8e00f4_idx'), models.Index(fields=['organization_id', 'sku'], name='products_organiz_bbcc44_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'sku'), name='unique_product_sku_per_org')],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('url', models.URLField(max_length=2048)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('media_type', models.CharField(default='image', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.product')),
            ],
            options={
                'db_table': 'product_media',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='ChannelPricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('channel', models.CharField(db_index=True, max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_pricing', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_pricing', to='products.productvariant')),
            ],
            options={
                'db_table': 'channel_pricing',
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('organization_id', 'sku'), name='unique_variant_sku_per_org'),
        ),
        migrations.AddConstraint(
            model_name='channelpricing',
            constraint=models.UniqueConstraint(fields=('organization_id', 'product', 'variant', 'channel'), name='unique_channel_pricing'),
        ),
    ]
