# Generated by Django 5.2.15 on 2026-06-06 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'domain_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'event_type'], name='domain_even_organiz_c254be_idx'), models.Index(fields=['organization_id', 'created_at'], name='domain_even_organiz_815729_idx'), models.Index(fields=['organization_id', 'processed'], name='domain_even_organiz_f0b9cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('handler_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_subscriptions',
                'unique_together': {('event_type', 'handler_path')},
            },
        ),
    ]
