# Generated by Django 5.2.15 on 2026-06-06 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('amazon', 'Amazon'), ('jumia', 'Jumia'), ('etsy', 'Etsy'), ('tiktok_shop', 'Tiktok Shop'), ('whatsapp_catalog', 'Whatsapp Catalog'), ('odoo', 'Odoo')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'platform_integrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'platform'], name='platform_in_organiz_6bb2e5_idx'), models.Index(fields=['organization_id', 'status'], name='platform_in_organiz_c6b75e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalProductMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='synced', max_length=50)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='integrations.platformintegration')),
            ],
            options={
                'db_table': 'external_product_mappings',
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'integration', 'sku'), name='unique_external_mapping_per_integration')],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('job_type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.platformintegration')),
            ],
            options={
                'db_table': 'sync_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'status'], name='sync_jobs_organiz_af7a97_idx'), models.Index(fields=['organization_id', 'job_type'], name='sync_jobs_organiz_c0efd3_idx')],
            },
        ),
    ]
