# Generated by Django 5.2.15 on 2026-06-06 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelBuffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('channel', models.CharField(db_index=True, max_length=50)),
                ('buffer_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'channel_buffers',
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'sku', 'channel'), name='unique_channel_buffer')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('variant_id', models.UUIDField(blank=True, null=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('quantity_available', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_levels',
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'sku'), name='unique_inventory_level_per_sku')],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('variant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entry_type', models.CharField(choices=[('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('release', 'Release'), ('sync', 'Channel Sync'), ('order_fulfillment', 'Order Fulfillment'), ('initial', 'Initial Stock')], max_length=30)),
                ('quantity_delta', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'stock_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'sku'], name='stock_ledge_organiz_1ab65e_idx'), models.Index(fields=['organization_id', 'created_at'], name='stock_ledge_organiz_000947_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('reference_type', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stock_reservations',
                'indexes': [models.Index(fields=['organization_id', 'reference_type', 'reference_id'], name='stock_reser_organiz_2f9a2c_idx')],
            },
        ),
    ]
