# Generated by Django 5.2.15 on 2026-06-06 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncFailureLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sync_job_id', models.UUIDField(db_index=True)),
                ('integration_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sync_failure_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('metric_type', models.CharField(db_index=True, max_length=100)),
                ('dimension', models.CharField(blank=True, db_index=True, max_length=100)),
                ('dimension_value', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(default='daily', max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'metric_snapshots',
                'indexes': [models.Index(fields=['organization_id', 'metric_type', 'period_start'], name='metric_snap_organiz_68f0ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'metric_type', 'dimension', 'dimension_value', 'period', 'period_start'), name='unique_metric_snapshot')],
            },
        ),
    ]
